### ISSUE TITLE
TCP Checksum calculation not working when BPF/XDP has data

### ISSUE THREAD

**Issue by incapdns** [xdp-project/xdp-tutorial#287] opened 2022-05-09 12:13 UTC
<h2>I have a question related to XDP / BPF that is also on stackoverflow, I will replicate it here</h2>

If the matter is off topic I would like to apologize in advance, if this is the case, please close the help request.

----------------------------
I want to understand how to fix my code to calculate TCP Checksum correctly

At the moment:
1. When <code>tcpdata_len</code> is zero, checksum is calculated correctly
2. When <code>tcpdata_len</code> is greater than zero, the checksum is incorrect, that is, there is a divergence from the expected to the current

My code to calculate the IP & TCP / UDP checksum:

    __attribute__((__always_inline__))
    static inline __u16 csum_fold_helper(__u64 csum) {
        int i;
    #pragma unroll
        for (i = 0; i < 4; i++) {
            if (csum >> 16)
                csum = (csum & 0xffff) + (csum >> 16);
        }
        return ~csum;
    }
    
    __attribute__((__always_inline__))
    static inline void ipv4_csum(void* data_start, int data_size, __u64* csum) {
        *csum = bpf_csum_diff(0, 0, data_start, data_size, *csum);
        *csum = csum_fold_helper(*csum);
    }
    
    __attribute__((__always_inline__))
    static inline void ipv4_l4_csum(void* data_start, __u32 data_size,
        __u64* csum, struct iphdr* iph) {
        __u32 tmp = 0;
        *csum = bpf_csum_diff(0, 0, &iph->saddr, sizeof(__be32), *csum);
        *csum = bpf_csum_diff(0, 0, &iph->daddr, sizeof(__be32), *csum);
        tmp = __builtin_bswap32((__u32)(iph->protocol));
        *csum = bpf_csum_diff(0, 0, &tmp, sizeof(__u32), *csum);
        tmp = __builtin_bswap32((__u32)(data_size));
        *csum = bpf_csum_diff(0, 0, &tmp, sizeof(__u32), *csum);
        *csum = bpf_csum_diff(0, 0, data_start, data_size, *csum);
        *csum = csum_fold_helper(*csum);
    }

The code call to calculate the IP Checksum and TCP Checksm: (after manually putting the destination and source IP and MAC Address):

    __u16 tcp_len = htons(iph->tot_len) - (iph->ihl * 4);
    
    __u16 tcpdata_len = htons(iph->tot_len) - (iph->ihl * 4) - (tcph->doff * 4);
    
    unsigned char gateway[ETH_ALEN];
    __builtin_memcpy(gateway, eth->h_source, ETH_ALEN);
    __builtin_memcpy(eth->h_source, eth->h_dest, ETH_ALEN);
    __builtin_memcpy(eth->h_dest, gateway, ETH_ALEN);
    
    __u32 saddr = iph->saddr;
    __u32 daddr = iph->daddr;
    
    iph->saddr = iph->daddr;
    iph->daddr = 4266428307;
    
    bpf_debug("DataLen: %i | %i", tcp_len, tcpdata_len);
    
    __u64 csum = 0;
    iph->check = 0;
    ipv4_csum(iph, sizeof(struct iphdr), &csum);
    iph->check = csum;
    
    csum = 0;
    tcph->check = 0;
    ipv4_l4_csum(tcph, tcp_len, &csum, iph);
    tcph->check = csum;

I understand that there are <b>other posts</b> on stackoverflow that teach how to correctly calculate the checksum, but I would like to use <b>this example</b> above as a basis, which in turn uses <b>bpf_csum_diff</b>. 

Important to note that I didn't find any post on stackoverflow that uses as a base like bpf_csum_diff to calculate the TCP checksum

<h2>That said, I leave my request below for those who will respond:</h2>

1. Please, also post the code with the necessary corrections, not just the explanation

2. [OPTIONAL] If possible, attach references (or explain) in your answer so that I can understand how this checksum calculation is done, I am in a very early stage of applications that involve networks in terms of raw packets

I would like to thank you in advance, and I apologize for my English (I'm using google translator).

**Comment by incapdns** [comment] 2022-05-09 12:17
If necessary, it's okay to use other codes (and not just bpf_csum_diff)

**Comment by tohojo** [comment] 2022-05-09 22:45
Hmm, only thing I can think of is that maybe your TCP payload has an odd
size? bpf_csum_diff() requires both from_size and to_size to be
multiples of 4, otherwise it'll return -EINVAL; and since you're not
checking the return value, that invalid return would just be put into
the checksum... To fix this, you'll have to check the length and handle
the last 1-3 bytes specially if the length is not a multiple of four.

**Comment by incapdns** [comment] 2022-05-09 23:40
Sorry, I couldn't follow your line of reasoning (I'm new to this area, I'm still learning), if you can share an example please.
Sorry for my english, i'm using google translator.

**Comment by tohojo** [comment] 2022-05-10 10:53
The `bpf_csum_diff()` helper has this check:

```
	if (unlikely(((from_size | to_size) & (sizeof(__be32) - 1)) ||
		     diff_size > sizeof(sp->diff)))
		return -EINVAL;
```

which you're likely hitting if your data payload is not a multiple of four (i.e., if `tcp_len % 4 != 0`), or if it's larger than `sizeof(sp->diff)` which is 512 bytes.

You'll have to update your `ipv4_l4_csum()` function to deal with this, by making multiple calls to `bpf_csum_diff()` and handling the last bytes specially...

**Comment by tohojo** [comment] 2022-05-10 11:12
Completely untested, but here's a modified function that does this:

```C
__attribute__((__always_inline__))
static inline void ipv4_l4_csum(void* data_start, __u32 data_size,
    __u64* csum, struct iphdr* iph) {
    __u32 trunc_size = data_size & ~3;
    __u32 tmp = 0;
    int i;
    *csum = bpf_csum_diff(0, 0, &iph->saddr, sizeof(__be32), *csum);
    *csum = bpf_csum_diff(0, 0, &iph->daddr, sizeof(__be32), *csum);
    tmp = __builtin_bswap32((__u32)(iph->protocol));
    *csum = bpf_csum_diff(0, 0, &tmp, sizeof(__u32), *csum);
    tmp = __builtin_bswap32((__u32)(data_size));
    *csum = bpf_csum_diff(0, 0, &tmp, sizeof(__u32), *csum);
    for (i = 0; i < 4 && trunc_size; i++) {
        __u32 sz = trunc_size > 512 ? 512 : trunc_size;
        *csum = bpf_csum_diff(0, 0, data_start, sz, *csum);
        data_start += sz;
        trunc_size -= sz;
    }

    if (data_size & 3) {
        __u8 bytes[4] = {};
        for (i = 0; i < data_size & 3; i++)
            bytes[i] = *(__u8*)data_start[trunc_size + i];
        *csum = bpf_csum_diff(0, 0, bytes, sizeof(bytes), *csum);
    }
    *csum = csum_fold_helper(*csum);
}
```

**Comment by incapdns** [comment] 2022-05-10 16:18
> The `bpf_csum_diff()` helper has this check:
> 
> ```
> 	if (unlikely(((from_size | to_size) & (sizeof(__be32) - 1)) ||
> 		     diff_size > sizeof(sp->diff)))
> 		return -EINVAL;
> ```
> 
> which you're likely hitting if your data payload is not a multiple of four (i.e., if `tcp_len % 4 != 0`), or if it's larger than `sizeof(sp->diff)` which is 512 bytes.
> 
> You'll have to update your `ipv4_l4_csum()` function to deal with this, by making multiple calls to `bpf_csum_diff()` and handling the last bytes specially...

I made a code from your explanation, can you explain to me why it doesn't work? (when is there data?)

```
__attribute__((__always_inline__))
static inline void ipv4_l4_csum(void* data_start, __u32 data_size,
    __u64* csum, struct iphdr* iph) {
    __u32 tmp = 0;
    *csum = bpf_csum_diff(0, 0, &iph->saddr, sizeof(__be32), *csum);
    *csum = bpf_csum_diff(0, 0, &iph->daddr, sizeof(__be32), *csum);
    tmp = __builtin_bswap32((__u32)(iph->protocol));
    *csum += tmp;
    tmp = __builtin_bswap32((__u32)(data_size));
    *csum += tmp;

    int n = 0;
    while (((data_size - n) & 3) != 0) {
        n++;
    }

    if (data_size > n) {
        *csum = bpf_csum_diff(0, 0, data_start, data_size - n, *csum);
    }

    unsigned char* restdata = (unsigned char*) data_start + (data_size - n);
    while (n > 0) {
        *csum += *restdata++;
        n--;
    }

    *csum = csum_fold_helper(*csum);
}
```

When I get home I'll test your code, and I'll get back, anyway I would like to thank you for helping me.

**Comment by tohojo** [comment] 2022-05-10 18:37
Lucas P ***@***.***> writes:

>> The `bpf_csum_diff()` helper has this check:
>> 
>> ```
>> 	if (unlikely(((from_size | to_size) & (sizeof(__be32) - 1)) ||
>> 		     diff_size > sizeof(sp->diff)))
>> 		return -EINVAL;
>> ```
>> 
>> which you're likely hitting if your data payload is not a multiple of four (i.e., if `tcp_len % 4 != 0`), or if it's larger than `sizeof(sp->diff)` which is 512 bytes.
>> 
>> You'll have to update your `ipv4_l4_csum()` function to deal with this, by making multiple calls to `bpf_csum_diff()` and handling the last bytes specially...
>
> I made a code from your explanation, can you explain to me why it
> doesn't work? (when is there data?)

Hmm, the checksum is computed on 16-bit integers, so you can't just sum
individual bytes; you'd have to left-shift the odd bytes...

> When I get home I'll test your code, and I'll get back, anyway I would
> like to thank you for helping me.

You're welcome!

**Comment by incapdns** [comment] 2022-05-10 22:42
> the checksum is computed on 16-bit integers
Thanks, now i'm using __u16 (I started using __u16)

> you'd have to left-shift the odd bytes
I added this manual check

```
__attribute__((__always_inline__))
static inline void ipv4_l4_csum(void* data_start, __u32 data_size,
    __u64* csum, struct iphdr* iph) {
    *csum = bpf_csum_diff(0, 0, &iph->saddr, sizeof(__be32), *csum);
    *csum = bpf_csum_diff(0, 0, &iph->daddr, sizeof(__be32), *csum);
    *csum += __builtin_bswap32((__u32)(iph->protocol));;
    *csum += __builtin_bswap32((__u32)(data_size));;

    int n = 0;
    while (((data_size - n) & 3) != 0) {
        n++;
    }

    if (data_size > n) {
        *csum = bpf_csum_diff(0, 0, data_start, data_size - n, *csum);
    }

    __u16* restdata = (__u16*)((u_char*) data_start + (data_size - n));
    while (n > 1) {
        *csum += *restdata++;
        n -= 2;
    }

    if (n == 1) {
        __u16 answer;
        *(u_char*)(&answer) = *(u_char*)restdata;
        *csum += answer;
    }

    *csum = csum_fold_helper(*csum);
}
```

The above code always returns a difference of 256 higher than expected, and when I try to manually decrease 256 in a condition if ((data_size - n) & 3) != 0, even doing the subtraction (-256) the difference becomes 255, example:
```
__attribute__((__always_inline__))
static inline void ipv4_l4_csum(void* data_start, __u32 data_size,
    __u64* csum, struct iphdr* iph) {
    *csum = bpf_csum_diff(0, 0, &iph->saddr, sizeof(__be32), *csum);
    *csum = bpf_csum_diff(0, 0, &iph->daddr, sizeof(__be32), *csum);
    *csum += __builtin_bswap32((__u32)(iph->protocol));;
    *csum += __builtin_bswap32((__u32)(data_size));;

    int minus = 0;

    int n = 0;
    while (((data_size - n) & 3) != 0) {
        n++;
    }

    if (data_size > n) {
        *csum = bpf_csum_diff(0, 0, data_start, data_size - n, *csum);
    }

    __u16* restdata = (__u16*)((u_char*) data_start + (data_size - n));
    while (n > 1) {
        *csum += *restdata++;
        n -= 2;
    }

    if (n == 1) {
        __u16 answer;
        *(u_char*)(&answer) = *(u_char*)restdata;
        *csum += answer;
    }

    bpf_debug("Minus: %i\n", minus);

    *csum = csum_fold_helper(*csum);
    *csum = *csum - minus;
}
```

If you can help me understand why this is happening :(

**Comment by tohojo** [comment] 2022-05-10 23:07
Hmm, so this:

```C

    if (n == 1) {
        __u16 answer;
        *(u_char*)(&answer) = *(u_char*)restdata;
        *csum += answer;
    }
```
actually puts the byte in the lower-order byte of `answer` on a little-endian system (so it ends up be equivalent to a regular assignment). You should probably be doing something like:

```C

    if (n == 1) {
        __u16 answer;
        answer = (*(u_char*)restdata) << 8;
        *csum += answer;
    }
```

**Comment by incapdns** [comment] 2022-05-10 23:18
![image](https://user-images.githubusercontent.com/40347728/167739776-f0073af4-40e9-4268-9ade-55dad7507d91.png)
Checksum Wireshark (Windows): 0x27af
Checksum Expected:  0x26af
Diff: 256

```
__attribute__((__always_inline__))
static inline void ipv4_l4_csum(void* data_start, __u32 data_size,
    __u64* csum, struct iphdr* iph) {
    *csum = bpf_csum_diff(0, 0, &iph->saddr, sizeof(__be32), *csum);
    *csum = bpf_csum_diff(0, 0, &iph->daddr, sizeof(__be32), *csum);
    *csum += __builtin_bswap32((__u32)(iph->protocol));;
    *csum += __builtin_bswap32((__u32)(data_size));;

    int n = 0;
    while (((data_size - n) & 3) != 0) {
        n++;
    }

    if (data_size > n) {
        *csum = bpf_csum_diff(0, 0, data_start, data_size - n, *csum);
    }

    __u16* restdata = (__u16*)((u_char*) data_start + (data_size - n));
    while (n > 1) {
        *csum += *restdata++;
        n -= 2;
    }

    if (n == 1) {
        __u16 answer;
        answer = (*(u_char*)restdata) << 8;
        *csum += answer;
    }

    *csum = csum_fold_helper(*csum);
}
```

One item I noticed was that the CSUM shown in Wireshark is different from bpf_debug (tcph->check), but I believe this is not very relevant to solve the problem (I only reported it just in case)

**Comment by tohojo** [comment] 2022-05-11 10:19
Okay, so that packet actually *does* have a size that's a multiple of four, so it's not hitting your odd-packet-length code at all.

Also, an off-by-256 error is most likely an off-by-one error in the wrong endianness. This could be caused by the folding helper not folding enough, because you're using a u64 for the csum. So try changing `__u64 csum` to `__u32 csum` everywhere and see if that helps? :)

**Comment by incapdns** [comment] 2022-05-11 12:53
> Okay, so that packet actually does have a size that's a multiple of four, so it's not hitting your odd-packet-length code at all.

The TCP tree way handshake is normal, but when I send some content (example of an HTTP request), the value of "n" is equal to 2, that is, it is falling into the condition of if(data_size - n) & 3 ! = 0

> Also, an off-by-256 error is most likely an off-by-one error in the wrong endianness. This could be caused by the folding helper not folding enough, because you're using a u64 for the csum. So try changing __u64 csum to __u32 csum everywhere and see if that helps? :)

![image](https://user-images.githubusercontent.com/40347728/167853970-4836f180-4079-4c5b-8e5e-26cca2aaffc3.png)

Checsum: 0xd7ae
Excepted: Checksum: 0x0837
Diff: 53111
_After switching from u32 to u64_

New code:
```
// SPDX-License-Identifier: (GPL-2.0 OR BSD-2-Clause)
// Copyright (c) 2018 Netronome Systems, Inc.
#define BPF_NO_GLOBAL_DATA

#include <stdbool.h>
#include <stddef.h>
#include <string.h>
#include <linux/bpf.h>
#include <linux/icmp.h>
#include <linux/if_ether.h>
#include <linux/if_vlan.h>
#include <linux/in.h>
#include <linux/ip.h>
#include <linux/tcp.h>
#include <linux/udp.h>
#include <linux/ipv6.h>
#include <endian.h>

#include "bpf_endian.h"
#include "bpf_helpers.h"
#include "jhash.h"
#include "common.h"
#include "parsing_helpers.h"

#include <stdint.h>

typedef union
{
    unsigned int   as_int;
    unsigned short as_short[2];
} INT2BYTE;


__attribute__((__always_inline__))
static inline __u16 csum_fold_helper(__u32 csum) {
    int i;
#pragma unroll
    for (i = 0; i < 4; i++) {
        if (csum >> 16)
            csum = (csum & 0xffff) + (csum >> 16);
    }
    return ~csum;
}

__attribute__((__always_inline__))
static inline void ipv4_csum(void* data_start, int data_size, __u32* csum) {
    if (data_size > 0) {
        *csum = bpf_csum_diff(0, 0, data_start, data_size, *csum);
        *csum = csum_fold_helper(*csum);
    }
}

typedef unsigned char u_char;


__attribute__((__always_inline__))
static inline void ipv4_l4_csum(void* data_start, __u32 data_size,
    __u32* csum, struct iphdr* iph) {
    *csum = bpf_csum_diff(0, 0, &iph->saddr, sizeof(__be32), *csum);
    *csum = bpf_csum_diff(0, 0, &iph->daddr, sizeof(__be32), *csum);
    *csum += __builtin_bswap32((__u32)(iph->protocol));;
    *csum += __builtin_bswap32((__u32)(data_size));;

    int n = 0;
    while (((data_size - n) & 3) != 0) {
        n++;
    }

    if (data_size > n && data_size - n > 0) {
        *csum = bpf_csum_diff(0, 0, data_start, data_size - n, *csum);
    }

    __u16* restdata = (__u16*)((u_char*)data_start + (data_size - n));
    while (n > 1) {
        *csum += *restdata++;
        n -= 2;
    }

    if (n == 1) {
        __u16 answer;
        answer = (*(u_char*)restdata) << 8;
        *csum += answer;
    }

    *csum = ~*csum;
}

struct bpf_map_def SEC("maps") CONNS = {
      .type = BPF_MAP_TYPE_HASH,
      .key_size = sizeof(__u32),
      .value_size = sizeof(__u32),
      .max_entries = 16776991,
      .map_flags = 0
};

SEC("prog")
int xdp_drop_benchmark_traffic(struct xdp_md* ctx)
{
    void* data_end = (void*)(long)ctx->data_end;
    void* data = (void*)(long)ctx->data;
    struct ethhdr* eth = data;

    if (data + sizeof(*eth) > data_end) {
        return XDP_PASS;
    }

    uint16_t h_proto = eth->h_proto;

    if (h_proto == htons(ETH_P_IP)) {
        struct iphdr* iph = data + sizeof(*eth);
        if (data + sizeof(*eth) + sizeof(*iph) > data_end) {
            return XDP_PASS;
        }

        if (iph->protocol != IPPROTO_TCP) {
            return XDP_PASS;
        }

        struct tcphdr* tcph = data + sizeof(*eth) + sizeof(*iph);
        if (data + sizeof(*eth) + sizeof(*iph) + sizeof(*tcph) > data_end) {
            return XDP_PASS;
        }

        __u16 tcp_len = htons(iph->tot_len) - (iph->ihl * 4);

        __u16 tcpdata_len = htons(iph->tot_len) - (tcph->doff * 4) - (iph->ihl * 4);

        if (tcph->dest == htons(65535))
        {
            unsigned char gateway[ETH_ALEN];
            __builtin_memcpy(gateway, eth->h_source, ETH_ALEN);
            __builtin_memcpy(eth->h_source, eth->h_dest, ETH_ALEN);
            __builtin_memcpy(eth->h_dest, gateway, ETH_ALEN);

            __u32 saddr = iph->saddr;
            __u32 daddr = iph->daddr;

            iph->saddr = iph->daddr;
            iph->daddr = 4266428307;

            __u32 csum = 0;
            iph->check = 0;
            ipv4_csum(iph, sizeof(struct iphdr), &csum);
            iph->check = csum;

            tcph->check = 0;
            ipv4_l4_csum(tcph, tcp_len, &csum, iph);
            tcph->check = csum;

            //bpf_debug("CSUM: %i | %i\n", csum, checksum(tcph, tcp_len));

            //const char* key = "SEQ+1:SPORT";

            __u32 key = ntohl(tcph->seq + tcph->source) + 1;

            bpf_map_update_elem(&CONNS, &key, &saddr, BPF_ANY);

            return XDP_TX;
        }
        else if (iph->saddr == 4266428307)
        {
            __u32 *ipv4;

            __u32 key = ntohl(tcph->ack_seq + tcph->dest);

            ipv4 = bpf_map_lookup_elem(&CONNS, &key);

            bpf_debug("Key From SV: %u", key);

            if (!ipv4)
            {
                bpf_debug("Fail: %u", key);
                return XDP_PASS;
            }

            unsigned char tmp[ETH_ALEN];
            __builtin_memcpy(tmp, eth->h_source, ETH_ALEN);
            __builtin_memcpy(eth->h_source, eth->h_dest, ETH_ALEN);
            __builtin_memcpy(eth->h_dest, tmp, ETH_ALEN);

            iph->saddr = iph->daddr;
            iph->daddr = *ipv4;

            __u32 csum = 0;
            iph->check = 0;
            ipv4_csum(iph, sizeof(struct iphdr), &csum);
            iph->check = csum;

            csum = 0;
            tcph->check = 0;
            ipv4_l4_csum(tcph, tcp_len, &csum, iph);
            tcph->check = csum;

            return XDP_TX;
        }
    }

    return XDP_PASS;
}

char _license[] SEC("license") = "GPL";
```

**Comment by tohojo** [comment] 2022-05-11 13:49
You're welcome! I'll close this issue, but feel free to reopen if needed...

**Closed by tohojo** 2022-05-11 13:49 UTC

**Comment by byxzone** [comment] 2022-11-18 12:35
> ipv4_l4_csum

when i use this code,i got an error:

```
  ; *csum = bpf_csum_diff(0, 0, data_start, data_size - n, *csum);
        714: (b7) r1 = 0
        715: (b7) r2 = 0
        716: (bf) r3 = r8
        717: (bf) r4 = r6
        718: (bf) r5 = r0
        719: (85) call bpf_csum_diff#28
        last_idx 719 first_idx 707
        regs=4 stack=0 before 718: (bf) r5 = r0
        regs=4 stack=0 before 717: (bf) r4 = r6
        regs=4 stack=0 before 716: (bf) r3 = r8
        regs=4 stack=0 before 715: (b7) r2 = 0
        R4 min value is negative, either use unsigned or 'var &= const'
        processed 294 insns (limit 1000000) max_states_per_insn 0 total_states 21 peak_states 21 mark_read 19
panic: runtime error: invalid memory address or nil pointer dereference
```

**Comment by 0x000001A4** [comment] 2024-09-22 00:06
@byxzone even with "ethtool -K eth0 tx off" the same verifier problem persists for me aswell, did you end up finding a solution?
